# serverless.yml
service: stocktwits-app

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  getTweets:
    handler: index.handler
    events:
      - http: 'GET /tweets/{proxy+}'

plugins:
  - serverless-offline #serverless-offline needs to be last in the list